version: 2
updates:
  - package-ecosystem: "npm"
    directory: "opa-react-demo/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "nestjs-demo/"
    schedule:
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # TicketHub Dependencies:
  - package-ecosystem: "npm"
    directory: "/tickethub/server/node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/tickethub/server/java"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
    ignore: # server/java doesn't compile when bumping these
      - dependency-name: "org.eclipse.jetty:*"
      - dependency-name: "org.glassfish.jersey.*"
  - package-ecosystem: "gradle"
    directory: "/tickethub/server/springboot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directory: "/tickethub/server/csharp"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/tickethub/client/react"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/tickethub/client/html"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /tickethub/
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/tickethub/tests/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all:
        patterns:
          - "*"
