services:
  react-demo:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - eopa

  eopa:
    image: ghcr.io/open-policy-agent/eopa:latest
    pull_policy: always
    ports:
      - "8181:8181"
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=debug
      - /policies
    volumes:
      - ./policies:/policies
